Repository paulocvasco/mercado-frescos-time-7, pull requests merged in 2022-06, with the labels that each got.

#24 Fix/architecture and names conflict issue #23
  go-web/cmd/server/controller/products.go
  go-web/cmd/server/controller/sections.go
  go-web/cmd/server/controller/warehouses.go
  go-web/internal/Seller/models/models.go
  go-web/internal/Seller/repository.go
  go-web/internal/employees/models/models.go
  go-web/internal/models/models.go
  go-web/internal/products/products.go
  go-web/internal/products/repository.go
  go-web/internal/products/services.go
  go-web/internal/sections/repository.go
  go-web/internal/sections/services.go
  go-web/internal/warehouse/repository.go
  go-web/internal/warehouse/services.go
  go-web/pkg/custom_errors/errors.go
Labels: fix

#30 Fix/req 02 warehouse
  go-web/cmd/server/controller/warehouses.go
  go-web/internal/models/models.go
  go-web/internal/warehouse/repository.go
  go-web/internal/warehouse/services.go
Labels: fix

#31 Feature/implement permanent db
  go-web/cmd/server/controller/warehouses.go
  go-web/cmd/server/routes/warehouse.go
  go-web/internal/models/models.go
  go-web/internal/warehouse/repository.go
  go-web/internal/warehouse/services.go
  go-web/pkg/db/database.go
Labels: enhancement

#42 Save data on file
  go-web/cmd/server/controller/warehouses.go
  go-web/cmd/server/routes/warehouse.go
  go-web/internal/models/models.go
  go-web/internal/warehouse/repository.go
  go-web/internal/warehouse/services.go
  go-web/pkg/db/database.go
Labels: fix

#41 Fix Bugs
  go-web/cmd/server/controller/buyers.go
  go-web/internal/buyer/repository.go
  go-web/internal/buyer/service.go
  go-web/pkg/custom_errors/errors.go
Labels: fix

#40 adicionando validação de campo único
  go-web/cmd/server/controller/sellers.go
  go-web/internal/Seller/repository.go
  go-web/internal/Seller/service.go
Labels: fix

#45 Req1/Sellers/Incluindo persistência com arquivo
  go-web/cmd/server/controller/sellers.go
  go-web/cmd/server/routes/sellers.go
  go-web/cmd/server/seller.db
  go-web/internal/Seller/repository.go
  go-web/internal/Seller/service.go
  go-web/internal/models/models.go
  go-web/pkg/db/database.go
Labels: feature

#56 Fix/id and getall return
  go-web/internal/products/repository.go
  go-web/internal/products/services.go
  go-web/pkg/custom_errors/errors.go
Labels: fix

#67 Feature/req 05 add tests
  .DS_Store
  go-web/.DS_Store
  go-web/cmd/.DS_Store
  go-web/cmd/server/controller/employees_test.go
  go-web/internal/.DS_Store
  go-web/internal/employees/mock.go
  go-web/internal/employees/service_test.go
Labels: test

#57 Feature/req 3/tests
  go-web/cmd/server/controller/coverage.out
  go-web/cmd/server/controller/sections_test.go
  go-web/coverage.out
  go-web/go.mod
  go-web/go.sum
  go-web/internal/sections/coverage.out
  go-web/internal/sections/mock/mockRepository/Repository.go
  go-web/internal/sections/mock/mockService/Service.go
  go-web/internal/sections/repository.go
  go-web/internal/sections/service_test.go
  go-web/internal/sections/services.go
Labels: feature

#66 Feature/req04 tests
  go-web/cmd/server/controller/product_test.go
  go-web/cmd/server/controller/products.go
  go-web/internal/products/mock/mockRepository/Repository.go
  go-web/internal/products/mock/mockService/Service.go
  go-web/internal/products/repository.go
  go-web/internal/products/services.go
  go-web/internal/products/services_test.go
Labels: test

#76 Requisito3/swag
  go-web/docs/sections.go
Labels: feature

#61 Requesito 1 seller/testes
  README.md
  go-web/cmd/server/controller/seller_test.go
  go-web/go.mod
  go-web/go.sum
  go-web/internal/Seller/mocks/mockRepository.go
  go-web/internal/Seller/mocks/mockService.go
  go-web/internal/Seller/service.go
  go-web/internal/Seller/service_test.go
Labels: test

#85 Fix/double code
  README.md
  go-web/cmd/server/controller/coverage.out
  go-web/cmd/server/seller.db
  go-web/coverage.out
  go-web/internal/buyer/service.go
  go-web/internal/sections/coverage.out
Labels: fix

#84 Fix warehouse pendencies
  .gitignore
  go-web/cmd/server/controller/warehouses.go
  go-web/cmd/server/controller/warehouses_test.go
  go-web/docs/warehouse.go
  go-web/go.mod
  go-web/go.sum
  go-web/internal/models/models.go
  go-web/internal/warehouse/mock/Service.go
  go-web/internal/warehouse/repository.go
  go-web/internal/warehouse/service_test.go
  go-web/internal/warehouse/services.go
  go-web/pkg/custom_errors/errors.go
  go-web/vendor/github.com/google/uuid/.travis.yml
  go-web/vendor/github.com/google/uuid/CONTRIBUTING.md
  go-web/vendor/github.com/google/uuid/CONTRIBUTORS
  go-web/vendor/github.com/google/uuid/LICENSE
  go-web/vendor/github.com/google/uuid/README.md
  go-web/vendor/github.com/google/uuid/dce.go
  go-web/vendor/github.com/google/uuid/doc.go
  go-web/vendor/github.com/google/uuid/hash.go
  go-web/vendor/github.com/google/uuid/marshal.go
  go-web/vendor/github.com/google/uuid/node.go
  go-web/vendor/github.com/google/uuid/node_js.go
  go-web/vendor/github.com/google/uuid/node_net.go
  go-web/vendor/github.com/google/uuid/null.go
  go-web/vendor/github.com/google/uuid/sql.go
  go-web/vendor/github.com/google/uuid/time.go
  go-web/vendor/github.com/google/uuid/util.go
  go-web/vendor/github.com/google/uuid/uuid.go
  go-web/vendor/github.com/google/uuid/version1.go
  go-web/vendor/github.com/google/uuid/version4.go
  go-web/vendor/modules.txt
Labels: fix

#88 changed the readme
  README.md
  go-web/db/mercado_fresco_db.sql
Labels: documentation

#89 Fix/vendor and errors
  .gitignore
  go-web/go.mod
  go-web/go.sum
  go-web/pkg/custom_errors/errors.go
  go-web/vendor/modules.txt
Labels: enhancement
