Repository paulocvasco/mercado-frescos-time-7, pull requests merged in 2022-07, with the labels that each got.

#98 handling requests and tests errors
  go-web/cmd/server/controller/sections.go
  go-web/internal/sections/service_test.go
  go-web/internal/sections/services.go
Labels: fix

#99 add database config file
  go-web/go.mod
  go-web/go.sum
  go-web/pkg/db/mysql.go
  go-web/vendor/modules.txt
Labels: feature

#108 Feature sprint3 req1/seller
  go-web/cmd/server/controller/locality.go
  go-web/cmd/server/controller/locality_test.go
  go-web/cmd/server/controller/reportSellers_test.go
  go-web/cmd/server/controller/reportsellers.go
  go-web/cmd/server/controller/seller_test.go
  go-web/cmd/server/controller/sellers.go
  go-web/cmd/server/main.go
  go-web/cmd/server/routes/localities.go
  go-web/cmd/server/routes/reportsellers.go
  go-web/cmd/server/routes/sellers.go
  go-web/docs/locality.go
  go-web/docs/seller.go
  go-web/go.mod
  go-web/go.sum
  go-web/internal/locality/mocks/Repository.go
  go-web/internal/locality/mocks/Service.go
  go-web/internal/locality/repository/mysql.go
  go-web/internal/locality/repository/mysql_test.go
  go-web/internal/locality/service.go
  go-web/internal/locality/service_test.go
  go-web/internal/models/models.go
  go-web/internal/reportsellers/mocks/Repository.go
  go-web/internal/reportsellers/mocks/Service.go
  go-web/internal/reportsellers/repository/mysql.go
  go-web/internal/reportsellers/repository/mysql_test.go
  go-web/internal/reportsellers/service.go
  go-web/internal/reportsellers/service_test.go
  go-web/internal/seller/repository/mysql.go
  go-web/internal/seller/repository/mysql_test.go
  go-web/pkg/db/mysql.go
  go-web/vendor/modules.txt
Labels: feature

#106 Feature/change db warehouse
  go-web/cmd/server/controller/carriers.go
  go-web/cmd/server/main.go
  go-web/cmd/server/routes/carriers.go
  go-web/cmd/server/routes/warehouse.go
  go-web/docs/carriers.go
  go-web/docs/warehouse.go
  go-web/go.mod
  go-web/internal/carriers/repository/mysql.go
  go-web/internal/carriers/repository/mysql_test.go
  go-web/internal/carriers/services.go
  go-web/internal/models/models.go
  go-web/internal/seller/repository/mysql_test.go
  go-web/internal/warehouse/repository/file.go
  go-web/internal/warehouse/repository/mysql.go
  go-web/internal/warehouse/repository/mysql_test.go
  go-web/internal/warehouse/services.go
  go-web/pkg/custom_errors/errors.go
  go-web/pkg/db/file.go
  go-web/pkg/db/mercado_fresco_db.sql
  go-web/pkg/db/mysql.go
Labels: documentation, enhancement, test

#101 Feature/sprint03 req04 products
  .gitignore
  go-web/cmd/server/controller/product_records.go
  go-web/cmd/server/controller/product_test.go
  go-web/cmd/server/controller/products.go
  go-web/cmd/server/main.go
  go-web/cmd/server/routes/product_records.go
  go-web/cmd/server/routes/products.go
  go-web/docs/product_records.go
  go-web/docs/products.go
  go-web/go.mod
  go-web/go.sum
  go-web/internal/models/models.go
  go-web/internal/product_records/repository/mysql.go
  go-web/internal/product_records/repository/mysql_test.go
  go-web/internal/product_records/repository/queries.go
  go-web/internal/product_records/service.go
  go-web/internal/products/mock/mockFileDb/mockFile.go
  go-web/internal/products/repository/file.go
  go-web/internal/products/repository/file_test.go
  go-web/internal/products/repository/mysql.go
  go-web/internal/products/repository/mysql_test.go
  go-web/internal/products/repository/queries.go
  go-web/internal/products/services.go
  go-web/internal/products/services_test.go
  go-web/pkg/custom_errors/errors.go
  go-web/pkg/db/mysql.go
  go-web/vendor/modules.txt
Labels: feature

#102 Feature/req03 bd implementation
  go-web/cmd/server/controller/product_batch.go
  go-web/cmd/server/controller/sections.go
  go-web/cmd/server/controller/sections_test.go
  go-web/cmd/server/main.go
  go-web/cmd/server/routes/product_batch.go
  go-web/cmd/server/routes/section.go
  go-web/docs/product_batch.go
  go-web/internal/productBatch/domain/product_batch_domain.go
  go-web/internal/productBatch/repository/mysql.go
  go-web/internal/productBatch/repository/mysql_test.go
  go-web/internal/productBatch/service.go
  go-web/internal/products/mock/mockfiledb/mockFile.go
  go-web/internal/sections/domain/section_domain.go
  go-web/internal/sections/repository.go
  go-web/internal/sections/repository/mysql.go
  go-web/internal/sections/repository/queries.go
  go-web/internal/sections/service.go
  go-web/internal/sections/service_test.go
  go-web/internal/sections/services.go
Labels: feature
